name: Fly Deploy

on:
  push:
    branches:
      - main

concurrency: 
  group: deploy-${GITHUB_REF_NAME}
  cancel-in-progress: true

env:
  FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}

jobs:
  deploy:
    name: Deploy app
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: superfly/flyctl-actions@1.5
        with:
          args: "deploy"
